---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: henvendelse-api
  namespace: default
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  webproxy: true
  liveness:
    path: henvendelse-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: henvendelse-api/internal/prometheus
  readiness:
    path: henvendelse-api/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://app.adeo.no/henvendelse-api
    - https://app.dev.adeo.no/henvendelse-api
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvhenvendelseapi
        mountPath: /var/run/secrets/nais.io/service_user
  secureLogs:
    enabled: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: "p"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts.adeo.no/SecurityTokenServiceProvider/"
    - name: MODIA_CLIENT_ID
      value: "modialogin-p"
    - name: SALESFORCE_CLIENT_ID
      value: "TODO TRENGER PROD VERSJON"
    - name: ISSO_DISCOVERY_URL
      value: "https://isso.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: AAD_V2_DISCOVERURI
      value: "https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration"
    - name: CXF_SECURE_LOG
      value: "enabled"
    - name: DOMENE_BRUKERDIALOG_BEHANDLEHENVENDELSE_V1_ENDPOINTURL
      value: "https://modapp.adeo.no/henvendelse/services/domene.Brukerdialog/BehandleHenvendelse_v1"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSE_V2_ENDPOINTURL
      value: "https://modapp.adeo.no/henvendelse/services/domene.Brukerdialog/Henvendelse_v2"
    - name: DOMENE_BRUKERDIALOG_SENDUTHENVENDELSE_V1_ENDPOINTURL
      value: "https://modapp.adeo.no/henvendelse/services/domene.Brukerdialog/SendUtHenvendelse_v1"
